language: java
install: true
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "janpopan"
    token:
       secure: "YDZpkJtOx+afEhJmenP675/9ILFKv9fOMTMJqbhl2HpXg/scmbAX3uEfzkroDE1qbu9CWRj06L1ASbySYzOAjCisG2PGMP6jUAjZvb0kTHx/r1dgguJAbdO15cfJCAyRyQTEHe7OOQ7qtkXi3mfss57ZdecnxjkGJATrWBIv0Cr5Mq1Z6jfEM8OBTo5ISTzYTZyAXkyKLyqiNUDpNhd3O6Pa8312vWAxEYUddzuanhzOxIw6eUZkDLCXuT3h6ErGKbjLYegqXs54kyzgVrLWHvKXSFn3rMzvbsb1Joo02zMmDSITG9szsIAN7sM3Pz5bGcOkZ9zQNObK1Zq9SCkp7VmiLtDWQmaargHK8mGB2ONvroWlqWLkMjk4HB0Mn4+tkjsIOW9tk2z+WPSnTZ3lUgPGwG71Ixtbgcu+ynHsZAx6HnO4gUK0tzu8wjJMRDEZMjHfTkPIoATmuRo3w/Sqyw4YfWBCtFhsrY6a7wHheu0F00NUuy4BXmMKqO1/gQUNLaiU73F7pH3NZM9on5DGPVJANHAc6e4Fhcim9wC9sqncXtte8i2yh94HCxUFuBxwBvVdeBSVpopGTjg6vtddRxZmxQZKq2dqLWgYHEMJKjS3qvgIYBzl5j1QCb7ExNkA008xuvgV0gIRUQ0GSQEwFr5X1XikgMNdOxp7NG1geQE="
script: 
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Janpopan_sonarqube-licensecheck -Pcoverage